Make osprofiler dependency really "soft"
In a37b5fe562a85787b74edc48c923aa6343490ec1 osprofiler was
changed to a soft requirement. However, if it is missing then
mistralclient will currently fail with:

AttributeError: 'NoneType' object has no attribute 'get_trace_id_headers'

This change checks to see if it was successfully imported before
it is used.

Depends-On: I1b61bd1de6811a5f65c2375dde956aafe33445b2
Change-Id: Ia742a4e55b35c5a787e4606ff2f91425dd156e5e
(cherry picked from commit d655e010b87c60cb62475324edfe3893c34ef711)